name: Java CI with Manual JUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download JUnit Console Launcher
      run: |
        curl -L -o junit-platform-console-standalone.jar \
          https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar

    - name: Compile code
      run: |
        mkdir -p out
        javac -d out -cp .:junit-platform-console-standalone.jar src/Lab1.java test/src/Lab1Test.java

    - name: Run tests
      run: |
        java -jar junit-platform-console-standalone.jar \
          --classpath out \
          --select-class Lab1Test \
          --disable-ansi-colors \
          --details-theme ascii
